import type { Metadata } from "next";
import { Outfit } from 'next/font/google';
import HomeNav from '@/components/Landing/HomeNav'
import Footer from '@/components/Landing/Footer'
import "../globals.css";

export const metadata: Metadata = {
  title: "FinTrack",
  description: "Generated by Tatin",
};

const outfit = Outfit({
  subsets: ['latin'],
  weight: '400',
})

export default function AppLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className={`min-h-screen bg-gradient-to-b from-[#101628] to-[#161F38] ${outfit.className}`}>
        <HomeNav />

            {children}

        <Footer />
    </div>
  );
}
