import type { Metadata } from "next";
import { Outfit } from 'next/font/google';
import { ClerkProvider } from "@clerk/nextjs";
import "../../globals.css";

export const metadata: Metadata = {
  title: "FinTrack",
  description: "Generated by Tatin",
};

const outfit = Outfit({
  subsets: ['latin'],
  weight: '400',
})

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider> 
        <div className={`min-h-screen bg-gradient-to-b from-[#101628] to-[#161F38] ${outfit.className}`}>
            {children}
        </div>
    </ClerkProvider>
  );
}
